version: "3.9"
services:
  redis:
    image: redis/redis-stack
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass testPassword
    environment:
      - name=value
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
